#!/bin/bash

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

exitcode=0
die() {
    echo "(pre-push) $@" >&2
    exitcode=1
}

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
    case "$local_ref" in
    refs/tags/[0-9]*)
        tag="${local_ref/refs\/tags\//}"
        # Mistakes I commonly make:
        # - Not updating CHANGES
        git show $local_sha:CHANGES | grep -q "^Version $tag" || die "Tag $tag not found in CHANGES"
        # - Not using an annotated tag
        test $(git cat-file -t "$local_ref") = "tag" || die "Tag $tag is not annotated"
        ;;
    esac
done

exit $exitcode
