#!/bin/bash
#
# Regenerate and upload a copy of the docs to github

set -e
set -x

cd "$(dirname $0)"
root=$(git rev-parse --show-toplevel)
cd "$root"

# Yeah, be safe
test -n "$(git status --porcelain)" && { echo "Uncommitted changes. Abort"; exit 1; }

make -C docs clean html
git checkout gh-pages
mv docs/_build/html/*.html .
mv docs/_build/html/_sources/*.txt _sources

# No changes
test -z "$(git status --porcelain)" && { git checkout master; exit 0; }

git add *.html _sources/*.txt
git commit
git push origin gh-pages
git checkout master
